apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: apps
type: Opaque
stringData:
  redis-password: "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: apps
type: Opaque
stringData:
  rabbitmq-user: "user"
  rabbitmq-password: "password"
