apiVersion: v1
kind: Service
metadata:
  name: master
  labels:
    io.kompose.service: master
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s-manifests/
    kompose.version: "1.35.0 (9532ceef3)"
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: master
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
    - name: "eureka"
      port: 8761
      targetPort: 8761