apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  namespace: apps
  labels:
    io.kompose.service: master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: master
  template:
    metadata:
      labels:
        io.kompose.service: master
    spec:
      nodeSelector:
        role: app
      containers:
        - name: master
          image: dagyss/master:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8761
          env:
            - name: EUREKA_FETCH_REGISTRY
              value: "false"
            - name: EUREKA_REGISTER_WITH_EUREKA
              value: "false"
            - name: SERVER_PORT
              value: "8761"
            - name: SPRING_APPLICATION_NAME
              value: master
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq.infra.svc.cluster.local
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-user
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-password
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      restartPolicy: Always