apiVersion: v1
kind: Service
metadata:
  name: master
  namespace: apps
  labels:
    io.kompose.service: master
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: master
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: eureka
      port: 8761
      targetPort: 8761