apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  labels:
    io.kompose.service: master
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s-manifests/
    kompose.version: "1.35.0 (9532ceef3)"
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: master
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: master
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s-manifests/
        kompose.version: "1.35.0 (9532ceef3)"
    spec:
      containers:
        - name: master
          image: dagyss/master:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PASSWORD
              value: password
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: user
            - name: SPRING_REDIS_HOST
              value: redis
            - name: SPRING_REDIS_PASSWORD
              value: password
            - name: SPRING_REDIS_PORT
              value: "6379"
          volumeMounts:
            - name: output-vol
              mountPath: /app/output
      restartPolicy: Always
      volumes:
        - name: output-vol
          emptyDir: {}
