apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data
  namespace: infra
  labels:
    io.kompose.service: rabbitmq-data
spec:
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: 100Mi
