apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s-manifests/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: reconstructor
  name: reconstructor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reconstructor
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s-manifests/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: reconstructor
    spec:
      containers:
        - image: dagyss/reconstructor:latest
          imagePullPolicy: Always
          name: reconstructor
          env:
            - name: EUREKA_CLIENT_FETCH
              value: "true"
            - name: EUREKA_CLIENT_REGISTER
              value: "true"
            - name: EUREKA_SERVICE_URL_DEFAULTZONE
              value: http://master:8761/eureka
            - name: GCS_BUCKET_NAME
              value: bucket-imagenes-sobel
            - name: SERVER_PORT
              value: "80"
            - name: SPRING_APPLICATION_NAME
              value: reconstructor
            - name: SPRING_REDIS_HOST
              value: redis
            - name: SPRING_REDIS_PASSWORD
              value: password
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: user
            - name: SPRING_RABBITMQ_PASSWORD
              value: password
      restartPolicy: Always
