apiVersion: v1
kind: Service
metadata:
  name: reconstructor
  namespace: apps
  labels:
    io.kompose.service: reconstructor
spec:
  type: ClusterIP
  selector:
    io.kompose.service: reconstructor
  ports:
    - name: http
      port: 80
      targetPort: 80