apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: infra
  labels:
    io.kompose.service: redis
spec:
  type: ClusterIP
  selector:
    io.kompose.service: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379