apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    io.kompose.service: worker
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s-manifests/
    kompose.version: "1.35.0 (9532ceef3)"
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker
  template:
    metadata:
      labels:
        io.kompose.service: worker
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s-manifests/
        kompose.version: "1.35.0 (9532ceef3)"
    spec:
      nodeSelector:
        role: worker
      tolerations:
        - key: "role"
          operator: "Equal"
          value: "worker"
          effect: "NoSchedule"
      containers:
        - name: worker
          image: dagyss/worker:latest
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PASS
              value: password
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: user
      restartPolicy: Always