name: Deploy to GKE

on:
  workflow_run:
    workflows: ["Terraform CI/CD"]   
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
       
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Install gke-gcloud-auth-plugin
        uses: simenandre/setup-gke-gcloud-auth-plugin@v1
  
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials gke-cluster --zone us-central1-a

      - name: Deploy manifests
        run: kubectl apply -f k8s-manifests/
